# Generated by Django 3.2.18 on 2023-04-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.CharField(blank=True, choices=[('Склад+Логистика', 'Склад+Логистика'), ('Логистика', 'Логистика'), ('Склад', 'Склад'), ('Обычный', 'Обычный'), ('Финансы', 'Финансы')], default='Обычный', max_length=100, null=True),
        ),
    ]
