# Generated by Django 3.2.18 on 2023-05-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_users_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(blank=True, choices=[('Логистика', 'Логистика'), ('Склад+Логистика', 'Склад+Логистика'), ('Склад', 'Склад'), ('Финансы', 'Финансы'), ('Обычный', 'Обычный')], default='Обычный', max_length=100, null=True),
        ),
    ]
