# Generated by Django 3.2.18 on 2023-05-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_users_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(blank=True, choices=[('Склад', 'Склад'), ('Логистика', 'Логистика'), ('Склад+Логистика', 'Склад+Логистика'), ('Обычный', 'Обычный'), ('Финансы', 'Финансы')], default='Обычный', max_length=100, null=True),
        ),
    ]
