# Generated by Django 3.2.18 on 2023-03-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('¥', '¥'), ('€', '€')], default='$', max_length=10),
        ),
    ]
