# Generated by Django 3.2.18 on 2023-03-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('На складе', 'На складе'), ('Частично отгружен', 'Частично отгружен'), ('Отгружен', 'Отгружен')], default='На складе', max_length=50),
        ),
    ]
