# Generated by Django 3.2.18 on 2023-04-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ContractNumber',
            field=models.CharField(blank=True, default='YY2018-30', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='priceBalance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='volumeBalance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='weightBalance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
