# Generated by Django 3.2.18 on 2023-05-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
        ('product', '0006_auto_20230413_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductToTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('comments', models.CharField(max_length=250)),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transports.transports')),
            ],
        ),
    ]
