# Generated by Django 3.2.18 on 2023-05-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_producttotransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttotransport',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.products'),
        ),
    ]
