# Generated by Django 3.2.18 on 2023-05-10 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_appeal_category'),
        ('product', '0008_producttotransport_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.appeal'),
        ),
    ]
