# Generated by Django 3.2.18 on 2023-04-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='currency',
            field=models.CharField(choices=[('Долл', 'Долл'), ('Юа', 'Юа'), ('Нал.юа', 'Нал.юа'), ('Евро', 'Евро'), ('Фапьяо юа', 'Фапьяо юа')], max_length=50),
        ),
    ]
