# Generated by Django 3.2.18 on 2023-04-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_appeal_category'),
        ('payment', '0002_alter_check_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.appeal'),
        ),
    ]
