# Generated by Django 3.2.18 on 2023-04-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_check_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='ContractNumber',
            field=models.CharField(blank=True, default='YY2018-30', max_length=150, null=True),
        ),
    ]
