# Generated by Django 3.2.18 on 2023-05-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_producttotransport'),
        ('payment', '0004_alter_check_contractnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='productToTransport_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.producttotransport'),
        ),
    ]
