# Generated by Django 3.2.18 on 2023-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_operation_producttotransport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='productPriceInUSD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='productPriceToPaking',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
