# Generated by Django 3.2.18 on 2023-05-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20230510_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='productPriceInUSDCurrency',
            field=models.CharField(blank=True, choices=[('$', '$'), ('¥', '¥'), ('€', '€')], default='$', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='productPriceToPakingCurrency',
            field=models.CharField(blank=True, choices=[('$', '$'), ('¥', '¥'), ('€', '€')], default='$', max_length=10, null=True),
        ),
    ]
