# Generated by Django 3.2.18 on 2023-03-08 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('contract', models.CharField(choices=[('Агентский', 'Агентский'), ('Поставка', 'Поставка')], max_length=50)),
                ('agent', models.CharField(choices=[('Фаст Импорт', 'Фаст Импорт'), ('Шеян', 'Шеян'), ('ТОНГАРД', 'ТОНГАРД')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Важное', 'Важное'), ('Оповещение', 'Оповещение'), ('Таможня', 'Таможня')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Важное', 'Важное'), ('Оповещение', 'Оповещение'), ('Товар', 'Товар'), ('Доставка', 'Доставка')], max_length=50)),
                ('doneAppeal', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.clients')),
            ],
        ),
    ]
