# Generated by Django 3.2.18 on 2023-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_appeal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='content',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='clients',
            name='agent',
            field=models.CharField(choices=[('Фаст Импорт', 'Фаст Импорт'), ('Шеян', 'Шеян'), ('ТОНГАРД', 'ТОНГАРД'), ('ПБ', 'ПБ')], max_length=50),
        ),
    ]
