# Generated by Django 3.2.18 on 2023-03-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230327_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='appeal-files/%Y/%m/%d'),
        ),
    ]
