# Generated by Django 3.2.18 on 2023-04-12 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_appeal_user_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=255)),
                ('file_comment', models.FileField(blank=True, null=True, upload_to='appeal-comments/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
