# Generated by Django 3.2.18 on 2023-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_appealcomments_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealcomments',
            name='content',
            field=models.CharField(max_length=1255),
        ),
    ]
