# Generated by Django 3.2.18 on 2023-05-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_appeal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='negativeBalance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='positiveBalance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
