# Generated by Django 3.2.18 on 2023-05-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230512_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='negativeBalance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='positiveBalance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
