# Generated by Django 3.2.18 on 2023-05-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Сборная', 'Сборная'), ('Авиа', 'Авиа'), ('Машина', 'Машина'), ('ЖД', 'ЖД'), ('Море', 'Море')], default='Сборная', max_length=100)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Сбор на складе', 'Сбор на складе'), ('СВХ', 'СВХ'), ('Таможня', 'Таможня'), ('Выпуск/разгрузка', 'Выпуск/разгрузка'), ('Отчетность на товар', 'Отчетность на товар'), ('Закрыта', 'Закрыта')], default='Сбор на складе', max_length=100)),
            ],
        ),
    ]
